//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.DOCUMENTs = new HashSet<DOCUMENT>();
        }
    
        public int CATE_ID { get; set; }
        public int INTYPE_ID { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_VI { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> SQUENCE_NUM { get; set; }
        public string NOTE { get; set; }
    
        public virtual INPUT_TYPE INPUT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENT> DOCUMENTs { get; set; }
    }
}
