//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LESSON()
        {
            this.LESS_CONDITION = new HashSet<LESS_CONDITION>();
            this.LESS_CONDITION1 = new HashSet<LESS_CONDITION>();
        }
    
        public int LESS_ID { get; set; }
        public string LESS_CODE { get; set; }
        public string LESS_NAME { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public Nullable<int> CATA_ID { get; set; }
        public Nullable<int> CREDIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string NOTE { get; set; }
    
        public virtual CATALOG CATALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LESS_CONDITION> LESS_CONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LESS_CONDITION> LESS_CONDITION1 { get; set; }
        public virtual PROGRAM PROGRAM { get; set; }
    }
}
