//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESS_CONDITION
    {
        public int ID { get; set; }
        public int LESS_NOW { get; set; }
        public Nullable<int> LESS_PRE { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual LESSON LESSON { get; set; }
        public virtual LESSON LESSON1 { get; set; }
    }
}
