//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.CONTACTs = new HashSet<CONTACT>();
            this.DOCUMENTs = new HashSet<DOCUMENT>();
        }
    
        public string STU_ID { get; set; }
        public Nullable<int> INTAKE_ID { get; set; }
        public int STUTYPE_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public int CATA_ID { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public string HCCSP_ID { get; set; }
        public string HCCS_EMPID { get; set; }
        public string BARCODE { get; set; }
        public string CANDI_ID { get; set; }
        public string FRIST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime BIRTH_DAY { get; set; }
        public string PLACE_BIRTH { get; set; }
        public string HOME_COUNTRY { get; set; }
        public int GENDER { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string PERSON_ID { get; set; }
        public string HOBBY { get; set; }
        public string PER_ADDRESS { get; set; }
        public string PER_CITY { get; set; }
        public string PER_COUNTRY { get; set; }
        public string PORTAL_ADDRESS { get; set; }
        public string PORTAL_CITY { get; set; }
        public string PROTAL_COUNTRY { get; set; }
        public string IMG { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual CATALOG CATALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT> CONTACTs { get; set; }
        public virtual CONTACT CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENT> DOCUMENTs { get; set; }
        public virtual PROGRAM PROGRAM { get; set; }
        public virtual TYPE_STUDENT TYPE_STUDENT { get; set; }
    }
}
