//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public Nullable<int> GENDER { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
