//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEAR_SEME
    {
        public int YEAR_ID { get; set; }
        public int SEM_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual YEAR YEAR { get; set; }
    }
}
